// Service Worker v9 — offline app shell (precache + cache-first)
// Versija: 2026-07-16
//
// Shell file list + version come from sw-precache.js (generated by
// scripts/build_sw_precache.py, which cache_bust.py invokes). Any shell file
// change produces a new SHELL_VERSION -> new cache name -> clean upgrade.
//
// v9 activate deliberately does NOT touch ppp-db-* caches: old browsers
// without DecompressionStream/IndexedDB still use the legacy network path
// whose db-worker may rely on them. v9 only removes its own stale
// ca-shell-* caches and the obsolete v8 sw-marker-* caches.

importScripts('sw-precache.js');

const SW_VERSION = 'v9-' + self.SHELL_VERSION;
const CACHE = 'ca-shell-' + self.SHELL_VERSION;
const V8_MARKER_PREFIX = 'sw-marker-'; // v8 left marker caches with this prefix

// Data owned by the app / IndexedDB layer — SW never caches these.
const PASSTHROUGH_PREFIXES = ['data/', 'packs/', 'transcripts/'];

// Scope-relative base path ('/' locally, '/ca-link-finder/' on GitHub Pages)
const BASE_PATH = new URL('./', self.location.href).pathname;

function relPath(pathname) {
    return pathname.indexOf(BASE_PATH) === 0
        ? pathname.slice(BASE_PATH.length)
        : pathname.replace(/^\//, '');
}

self.addEventListener('install', function (event) {
    event.waitUntil((async function () {
        console.log('[SW ' + SW_VERSION + '] Install — precaching ' +
            self.PRECACHE.length + ' shell files');
        const cache = await caches.open(CACHE);
        const CHUNK = 50;
        let missing = 0;
        for (let i = 0; i < self.PRECACHE.length; i += CHUNK) {
            const chunk = self.PRECACHE.slice(i, i + CHUNK);
            await Promise.all(chunk.map(async function (url) {
                // Individual fetch instead of addAll: a single 404/network
                // hiccup must not brick the whole install.
                try {
                    const resp = await fetch(url, { cache: 'no-cache' });
                    if (resp.ok) {
                        await cache.put(url, resp);
                    } else {
                        missing++;
                        console.warn('[SW ' + SW_VERSION + '] Precache skip (' +
                            resp.status + '): ' + url);
                    }
                } catch (err) {
                    missing++;
                    console.warn('[SW ' + SW_VERSION + '] Precache skip (fetch failed): ' + url);
                }
            }));
        }
        if (missing) {
            console.warn('[SW ' + SW_VERSION + '] Install done with ' + missing + ' missing files');
        }
        await self.skipWaiting();
    })());
});

self.addEventListener('activate', function (event) {
    event.waitUntil((async function () {
        const names = await caches.keys();
        await Promise.all(names.map(function (name) {
            const staleShell = name.indexOf('ca-shell-') === 0 && name !== CACHE;
            const v8Marker = name.indexOf(V8_MARKER_PREFIX) === 0;
            // NOTE: ppp-db-* and any other caches are intentionally left
            // alone (legacy fallback path for old browsers). No client
            // reload, no blanket wipe.
            if (staleShell || v8Marker) {
                console.log('[SW ' + SW_VERSION + '] Deleting stale cache: ' + name);
                return caches.delete(name);
            }
            return Promise.resolve();
        }));
        await self.clients.claim();
        console.log('[SW ' + SW_VERSION + '] Activated');
    })());
});

self.addEventListener('fetch', function (event) {
    const request = event.request;
    if (request.method !== 'GET') return;                 // passthrough

    const url = new URL(request.url);
    if (url.origin !== self.location.origin) return;      // cross-origin passthrough

    const rel = relPath(url.pathname);
    for (let i = 0; i < PASSTHROUGH_PREFIXES.length; i++) {
        if (rel.indexOf(PASSTHROUGH_PREFIXES[i]) === 0) return; // network only
    }

    // Navigations (app root, guide/{lang}/): network-first so updated
    // index.html (with fresh ?v= hashes) is seen immediately when online;
    // cached shell copy when offline.
    if (request.mode === 'navigate' || url.pathname.endsWith('/index.html')) {
        event.respondWith((async function () {
            try {
                return await fetch(request, { cache: 'no-cache' });
            } catch (err) {
                // Directory URL -> its index.html precache entry. Cached keys
                // carry ?v= hashes, so match ignoring the search part.
                let target = url.pathname;
                if (target.endsWith('/')) target += 'index.html';
                const hit = await caches.match(target, { ignoreSearch: true });
                if (hit) return hit;
                // Last resort: app shell root page
                const root = await caches.match(BASE_PATH + 'index.html', { ignoreSearch: true });
                if (root) return root;
                throw err;
            }
        })());
        return;
    }

    // Static assets: cache-first. Precache keys are stored WITH ?v=<hash8>
    // (same sha256[:8] as cache_bust.py), and only ONE version of each path
    // exists per cache, so matching with ignoreSearch:true is safe and also
    // covers refs without ?v= (fonts.css woff2 refs, vendor libs,
    // guide/menu-data.js?v=1).
    event.respondWith((async function () {
        const hit = await caches.match(request, { ignoreSearch: true });
        if (hit) return hit;
        const resp = await fetch(request);
        if (resp && resp.ok && (resp.type === 'basic' || resp.type === 'default')) {
            const cache = await caches.open(CACHE);
            cache.put(request, resp.clone()).catch(function () {});
        }
        return resp;
    })());
});
