// Service Worker v10 — offline app shell (precache + cache-first)
// Versija: 2026-07-27c
//
// 2026-07-27c: REQUIRED_SHELL — a precache miss on the Brotli decoder now
// FAILS the install instead of activating a shell that cannot read the
// device's own library. Rationale at the constant. (Codex audit HIGH-2.)
//
// 2026-07-27b: shell gained js/codec.js, js/vendor/brotli-dec.js and
// js/vendor/brotli-dec.wasm (Brotli decoding for the next corpus generation).
// The .wasm MUST be precached even though codec.js loads it lazily: a device
// that is already installed and offline receives a Brotli delta with no
// network left to fetch a decoder from. Both vendor files are referenced
// without ?v= (codec.js injects them at runtime), so they ride the same
// loose-match path as js/vendor/sql-wasm.{js,wasm}.
//
// 2026-07-27: shell files changed (js/db.js) and the last two hand-written
// '?v=' labels became content hashes — see the static-asset section below.
// Bumping the date is what makes the browser's SW update check see a byte
// difference; sw-precache.js content alone is invisible to it.
//
// 2026-07-26: bumped alongside sw-precache.js (js/app.js, js/i18n.js and
// others changed in commit 0f09795 without a cache-bust pass — see the
// staging session archive). This comment-only edit is what actually makes
// the browser's SW update check see a byte difference: importScripts()
// content (sw-precache.js/SHELL_VERSION) is invisible to that check on its
// own, so a SHELL_VERSION bump alone never reaches a browser that already
// has this exact sw.js installed. Bump this line whenever any precached
// shell file changes, not just when sw.js's own logic changes.
//
// Shell file list + version come from sw-precache.js (generated by
// scripts/build_sw_precache.py, which cache_bust.py invokes). Any shell file
// change produces a new SHELL_VERSION -> new cache name -> clean upgrade.
//
// v9 activate deliberately does NOT touch ppp-db-* caches: old browsers
// without DecompressionStream/IndexedDB still use the legacy network path
// whose db-worker may rely on them. v9 only removes its own stale
// ca-shell-* caches and the obsolete v8 sw-marker-* caches.
//
// v10: the online (not-yet-installed) core DB gz files under data/ (meta,
// extras, sentences) are now cache-first instead of network-only, so a
// repeat online visit opens instantly instead of re-downloading the meta DB
// every time ("Загрузка базы данных" on every visit). packs/ and
// transcripts/ stay passthrough — those are owned by the IndexedDB offline
// library. data/manifest.json and data/db-versions.json stay network-first
// (no ?v= hash of their own — db-versions.json IS the hash source, and
// manifest.json drives delta-update checks, so both must be read fresh).

importScripts('sw-precache.js');

// AUTO-STAMPED by scripts/build_sw_precache.py — do not edit by hand.
//
// Exists so that changing the precached SHELL also changes sw.js's OWN
// bytes. The browser's Service Worker update check (the thing that decides
// whether to fetch/install a NEW worker at all) byte-compares the response
// for the registered script URL itself (js/app.js registers 'sw.js') against
// what it already has installed — it never looks inside anything sw.js
// merely imports. A SHELL_VERSION bump living only in sw-precache.js
// (fetched via importScripts() two lines up) is therefore INVISIBLE to that
// check on its own: a browser that already has this exact sw.js keeps it,
// forever, no matter how many times sw-precache.js's content changes
// underneath it. Three staging commits (2ebc26b, d13be0a, 2787bb9,
// 2026-07-27) each changed js/ files, and none of them reached an
// already-installed device — this constant, kept in sync with
// self.SHELL_VERSION on every cache_bust.py run, is what makes the NEXT such
// change actually visible (Codex HIGH-2, 2026-07-28).
const SW_SHELL_STAMP = 'a88a80de2459';
if (typeof self.SHELL_VERSION === 'string' && self.SHELL_VERSION !== SW_SHELL_STAMP) {
    // Non-fatal: an install-blocking throw here would be worse than serving
    // a mismatched shell for one cycle. This means scripts/cache_bust.py was
    // not run (or failed) after the last shell-file edit — see the
    // sw-precache.js drift gate in tests/cache-bust-gate.spec.js.
    console.error('sw.js SW_SHELL_STAMP (' + SW_SHELL_STAMP + ') does not match ' +
        'sw-precache.js SHELL_VERSION (' + self.SHELL_VERSION + ') — ' +
        'scripts/cache_bust.py was not run after the last shell-file edit.');
}

const SW_VERSION = 'v10-' + self.SHELL_VERSION;
const CACHE = 'ca-shell-' + self.SHELL_VERSION;
const V8_MARKER_PREFIX = 'sw-marker-'; // v8 left marker caches with this prefix

// Raw offline-library content owned by IndexedDB — SW never caches these.
//
// data/shards/ joined this list on 2026-07-27 after measuring a real full
// install: the shell cache had grown to 232 MB because the v10 "data/ is
// cache-first" rule also caught the 21 sentence shards, so the device ended up
// holding 342 MB in IndexedDB AND a second 191 MB copy in the SW cache — 574 MB
// for a 342 MB install. Nothing reads the SW copy: shard fetches happen during
// the install (which writes them to IndexedDB) and, since online sentence search
// was removed, nowhere else. Pure duplication.
//
// The three core DBs (meta, extras, sentences) stay cache-first on purpose —
// that is what makes a repeat visit open instantly for someone who has NOT
// installed the library.
const PASSTHROUGH_PREFIXES = ['packs/', 'transcripts/', 'data/shards/'];

// Shell files whose absence is UNRECOVERABLE, so a precache miss on them must
// FAIL the install instead of activating a crippled worker.
//
// Everything else in PRECACHE degrades: a missing font renders in a fallback
// face, a missing guide page is one dead link, and the network heals it on the
// next online visit. The Brotli decoder does not degrade. Once a `br`
// generation is published, a device that installed the library has NO network
// left when it goes offline, and every shard it owns becomes undecodable —
// "Brotli decoder failed to load", permanently, with the data sitting right
// there in IndexedDB. The install path tolerated exactly that: a transient
// failure on this one file bumped `missing`, warned, and called skipWaiting()
// anyway, and activate then deleted the previous WORKING shell cache.
// (Codex audit HIGH-2, 2026-07-27.)
//
// Failing the install is the safe direction: the event rejects, the browser
// discards this worker, the previous worker and its shell cache keep serving,
// and the update is retried on a later visit. Never a half shell.
//
// The list is GENERATED into sw-precache.js by scripts/build_sw_precache.py,
// from the SAME scan that produces PRECACHE — never hand-maintained here. A
// hand-kept copy stops matching the first time a file is renamed, and since a
// miss on these is fatal to the install, a stale name would either block every
// device's updates forever or quietly stop protecting anything. The build
// script fails outright if a listed path is not in the shell scan.
//
// It covers js/codec.js + js/vendor/brotli-dec.* (no Brotli decode = an
// installed offline device cannot read shards it already owns) and
// js/vendor/sql-wasm.* (no sql.js = no database opens at all — Rājan,
// 2026-07-27).
const REQUIRED_SHELL = self.REQUIRED_SHELL || [];
if (!self.REQUIRED_SHELL) {
    // Only reachable if this sw.js is deployed beside a sw-precache.js
    // generated before the list existed. Degrade to the old tolerant behaviour
    // rather than brick installs — but say so, it is a build/deploy mismatch.
    console.error('[SW] sw-precache.js has no REQUIRED_SHELL — ' +
        'regenerate it with scripts/build_sw_precache.py');
}

function isRequiredShell(precacheUrl) {
    return REQUIRED_SHELL.indexOf(String(precacheUrl).split('?')[0]) !== -1;
}

// data/ files with no ?v= hash of their own — must always be read fresh.
const NETWORK_FIRST_DATA = ['data/manifest.json', 'data/db-versions.json'];

const DATA_PREFIX = 'data/';

// Scope-relative base path ('/' locally, '/ca-link-finder/' on GitHub Pages)
const BASE_PATH = new URL('./', self.location.href).pathname;

function relPath(pathname) {
    return pathname.indexOf(BASE_PATH) === 0
        ? pathname.slice(BASE_PATH.length)
        : pathname.replace(/^\//, '');
}

self.addEventListener('install', function (event) {
    event.waitUntil((async function () {
        console.log('[SW ' + SW_VERSION + '] Install — precaching ' +
            self.PRECACHE.length + ' shell files');
        const cache = await caches.open(CACHE);
        const CHUNK = 50;
        let missing = 0;
        const missingRequired = [];
        for (let i = 0; i < self.PRECACHE.length; i += CHUNK) {
            const chunk = self.PRECACHE.slice(i, i + CHUNK);
            await Promise.all(chunk.map(async function (url) {
                // Individual fetch instead of addAll: a single 404/network
                // hiccup must not brick the whole install — EXCEPT for
                // REQUIRED_SHELL, which is collected and re-raised below.
                try {
                    const resp = await fetch(url, { cache: 'no-cache' });
                    if (resp.ok) {
                        await cache.put(url, resp);
                    } else {
                        missing++;
                        if (isRequiredShell(url)) missingRequired.push(url);
                        console.warn('[SW ' + SW_VERSION + '] Precache skip (' +
                            resp.status + '): ' + url);
                    }
                } catch (err) {
                    missing++;
                    if (isRequiredShell(url)) missingRequired.push(url);
                    console.warn('[SW ' + SW_VERSION + '] Precache skip (fetch failed): ' + url);
                }
            }));
        }
        if (missingRequired.length) {
            // Leave NOTHING behind: this cache name is derived from
            // SHELL_VERSION, so a half-filled copy of it would be adopted
            // wholesale by the next install of the same shell and its holes
            // would look precached forever.
            await caches.delete(CACHE);
            throw new Error('[SW ' + SW_VERSION + '] Install ABORTED — required shell file(s) ' +
                'could not be precached: ' + missingRequired.join(', ') +
                '. Keeping the previous worker; the update will be retried.');
        }
        if (missing) {
            console.warn('[SW ' + SW_VERSION + '] Install done with ' + missing + ' missing files');
        }
        await self.skipWaiting();
    })());
});

self.addEventListener('activate', function (event) {
    event.waitUntil((async function () {
        const names = await caches.keys();
        await Promise.all(names.map(function (name) {
            const staleShell = name.indexOf('ca-shell-') === 0 && name !== CACHE;
            const v8Marker = name.indexOf(V8_MARKER_PREFIX) === 0;
            // NOTE: ppp-db-* and any other caches are intentionally left
            // alone (legacy fallback path for old browsers). No client
            // reload, no blanket wipe.
            if (staleShell || v8Marker) {
                console.log('[SW ' + SW_VERSION + '] Deleting stale cache: ' + name);
                return caches.delete(name);
            }
            return Promise.resolve();
        }));
        await self.clients.claim();
        console.log('[SW ' + SW_VERSION + '] Activated');
    })());
});

self.addEventListener('fetch', function (event) {
    const request = event.request;
    if (request.method !== 'GET') return;                 // passthrough

    const url = new URL(request.url);
    if (url.origin !== self.location.origin) return;      // cross-origin passthrough

    const rel = relPath(url.pathname);
    for (let i = 0; i < PASSTHROUGH_PREFIXES.length; i++) {
        if (rel.indexOf(PASSTHROUGH_PREFIXES[i]) === 0) return; // network only
    }

    // manifest.json / db-versions.json: always network-first. They carry no
    // ?v= hash of their own (db-versions.json IS the hash source used to
    // build every other data/ URL's ?v=), so a stale cached copy would
    // silently pin the app to an old DB forever. Cache is only a
    // last-resort offline fallback.
    if (NETWORK_FIRST_DATA.indexOf(rel) !== -1) {
        event.respondWith((async function () {
            try {
                const resp = await fetch(request, { cache: 'no-store' });
                if (resp && resp.ok) {
                    const cache = await caches.open(CACHE);
                    cache.put(request, resp.clone()).catch(function () {});
                }
                return resp;
            } catch (err) {
                const hit = await caches.match(request, { ignoreSearch: true });
                if (hit) return hit;
                throw err;
            }
        })());
        return;
    }

    // Other data/ files (core DB gz: meta, extras, sentences): cache-first,
    // but matched by the FULL url including ?v=<hash> — NOT ignoreSearch.
    // Their hash changes when the underlying data changes, so a new ?v=
    // must be treated as a cache miss and re-fetched (ignoreSearch would
    // wrongly return the old cached bytes for the new hash). The stale
    // same-path entry is evicted once the new one lands, so old DB versions
    // don't accumulate in the cache.
    if (rel.indexOf(DATA_PREFIX) === 0) {
        event.respondWith((async function () {
            const hit = await caches.match(request); // exact match, incl. ?v=
            if (hit) return hit;
            const resp = await fetch(request);
            if (resp && resp.ok && (resp.type === 'basic' || resp.type === 'default')) {
                const cache = await caches.open(CACHE);
                const keys = await cache.keys();
                await Promise.all(keys.map(function (k) {
                    const kUrl = new URL(k.url);
                    if (kUrl.pathname === url.pathname && kUrl.search !== url.search) {
                        return cache.delete(k);
                    }
                    return Promise.resolve();
                }));
                cache.put(request, resp.clone()).catch(function () {});
            }
            return resp;
        })());
        return;
    }

    // Navigations (app root, guide/{lang}/): network-first so updated
    // index.html (with fresh ?v= hashes) is seen immediately when online;
    // cached shell copy when offline.
    if (request.mode === 'navigate' || url.pathname.endsWith('/index.html')) {
        event.respondWith((async function () {
            try {
                return await fetch(request, { cache: 'no-cache' });
            } catch (err) {
                // Directory URL -> its index.html precache entry. Cached keys
                // carry ?v= hashes, so match ignoring the search part.
                let target = url.pathname;
                if (target.endsWith('/')) target += 'index.html';
                const hit = await caches.match(target, { ignoreSearch: true });
                if (hit) return hit;
                // Last resort: app shell root page
                const root = await caches.match(BASE_PATH + 'index.html', { ignoreSearch: true });
                if (root) return root;
                throw err;
            }
        })());
        return;
    }

    // Static assets: cache-first. Precache keys are stored WITH ?v=<hash8>
    // (same sha256[:8] as cache_bust.py), and only ONE version of each path
    // exists per cache — but "per cache" is the catch. Navigations are
    // network-first, so a fresh index.html carrying NEW ?v= hashes can render
    // while the PREVIOUS shell cache is still the active one (the new SW is
    // installed but has not activated yet). Matching with ignoreSearch:true in
    // that window hands the new index.html the OLD app.js, and the page breaks
    // in a way no test sees. Codex audit, 2026-07-26.
    //
    // So a request carrying an explicit ?v= must be satisfied EXACTLY or go to
    // the network. That rule only holds while EVERY ?v= in the app is a content
    // hash; two references used hand-written labels instead
    // (guide/menu-data.js?v=1, js/db-worker.js?v=cache5) and therefore missed
    // this exact match on every single load — one wasted round trip plus a
    // duplicate cache entry per generation. Both are content-hashed by
    // scripts/cache_bust.py now (TARGETS and JS_REFS respectively); do not
    // reintroduce a literal ?v= label anywhere.
    //
    // The loose match survives as the offline last resort, and stays the normal
    // path for references carrying no ?v= at all: css/fonts/fonts.css and its
    // woff2 urls, js/vendor/{papaparse,xlsx.full,sql-wasm}.js, manifest.json
    // and the icons.
    const versioned = url.searchParams.has('v');
    event.respondWith((async function () {
        const hit = await caches.match(request, { ignoreSearch: !versioned });
        if (hit) return hit;
        try {
            const resp = await fetch(request);
            if (resp && resp.ok && (resp.type === 'basic' || resp.type === 'default')) {
                const cache = await caches.open(CACHE);
                cache.put(request, resp.clone()).catch(function () {});
            }
            return resp;
        } catch (err) {
            // Offline and this exact version is not cached. A stale copy of the
            // right file beats a dead page — but only as a last resort, never
            // ahead of the network the way it used to be.
            if (versioned) {
                const loose = await caches.match(request, { ignoreSearch: true });
                if (loose) return loose;
            }
            throw err;
        }
    })());
});
