#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_guide_menu.py — Generate guide/menu-data.js from guide/<lang>/index.html.

WHY: The "33 Features" button opens a dropdown menu listing the 9 function
groups (A-I) and, under each, the localized function names. That menu needs a
compact data source per language. Rather than duplicate the guide's GROUPS/ITEMS
by hand, this script extracts them straight from each guide page so the menu can
never drift from the guide.

WHAT: Reads the inline `const GROUPS = [...]` and `const ITEMS = [...]` arrays
from each guide/<lang>/index.html, keeps only what the menu needs (group letter
+ name; item n + group + title), and writes guide/menu-data.js exposing
`window.PPP_GUIDE_MENU`.

HOW: Regex extraction (the arrays are hand-authored JS literals, not JSON, and
some `t` values contain escaped quotes). Validates 9 groups + 33 items per lang.

WHERE: run from anywhere with `python scripts/build_guide_menu.py`; paths are
resolved relative to this file's location (staging root).
"""
import json
import os
import re
import sys

LANGS = ["en", "ru", "lv", "it", "fr", "es"]
EXPECTED_GROUPS = 9
EXPECTED_ITEMS = 33

# staging/ root = parent of this script's directory (scripts/).
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# GROUPS: { letter: "X", name: "..." }
GROUP_RE = re.compile(
    r'\{\s*letter:\s*"((?:[^"\\]|\\.)*)"\s*,\s*name:\s*"((?:[^"\\]|\\.)*)"\s*\}'
)
# ITEMS: capture n (int), g (letter), t (string, may contain \" and \\).
ITEM_N_RE = re.compile(r'n:\s*(\d+)')
ITEM_G_RE = re.compile(r'g:\s*"((?:[^"\\]|\\.)*)"')
ITEM_T_RE = re.compile(r't:\s*"((?:[^"\\]|\\.)*)"')


def unescape(s):
    """Unescape \\" -> " and \\\\ -> \\ (JS string literal -> plain text)."""
    return s.replace('\\"', '"').replace('\\\\', '\\')


def slice_array(html, marker):
    """Return the text between `const <marker> = [` and its matching top-level `]`."""
    start = html.find(marker)
    if start == -1:
        return None
    bracket = html.find('[', start)
    if bracket == -1:
        return None
    depth = 0
    for i in range(bracket, len(html)):
        c = html[i]
        if c == '[':
            depth += 1
        elif c == ']':
            depth -= 1
            if depth == 0:
                return html[bracket:i + 1]
    return None


def extract_groups(html):
    block = slice_array(html, 'const GROUPS')
    if block is None:
        return []
    groups = []
    for letter, name in GROUP_RE.findall(block):
        groups.append({"l": unescape(letter), "name": unescape(name)})
    return groups


def extract_items(html):
    block = slice_array(html, 'const ITEMS')
    if block is None:
        return []
    items = []
    # Split into individual { ... } object literals at top level.
    depth = 0
    obj_start = None
    for i, c in enumerate(block):
        if c == '{':
            if depth == 0:
                obj_start = i
            depth += 1
        elif c == '}':
            depth -= 1
            if depth == 0 and obj_start is not None:
                obj = block[obj_start:i + 1]
                n_m = ITEM_N_RE.search(obj)
                g_m = ITEM_G_RE.search(obj)
                t_m = ITEM_T_RE.search(obj)
                if n_m and g_m and t_m:
                    items.append({
                        "n": int(n_m.group(1)),
                        "g": unescape(g_m.group(1)),
                        "t": unescape(t_m.group(1)),
                    })
                obj_start = None
    return items


def main():
    data = {}
    ok = True
    for lang in LANGS:
        path = os.path.join(ROOT, "guide", lang, "index.html")
        if not os.path.isfile(path):
            sys.stderr.write("WARNING: missing guide file: %s\n" % path)
            ok = False
            continue
        with open(path, "r", encoding="utf-8") as f:
            html = f.read()
        groups = extract_groups(html)
        items = extract_items(html)
        if len(groups) != EXPECTED_GROUPS:
            sys.stderr.write(
                "WARNING: %s has %d groups, expected %d\n"
                % (lang, len(groups), EXPECTED_GROUPS)
            )
            ok = False
        if len(items) != EXPECTED_ITEMS:
            sys.stderr.write(
                "WARNING: %s has %d items, expected %d\n"
                % (lang, len(items), EXPECTED_ITEMS)
            )
            ok = False
        data[lang] = {"groups": groups, "items": items}

    payload = json.dumps(data, ensure_ascii=False, indent=1)
    out_path = os.path.join(ROOT, "guide", "menu-data.js")
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(
            "// AUTO-GENERATED by scripts/build_guide_menu.py from "
            "guide/<lang>/index.html — do not edit by hand.\n"
        )
        f.write("window.PPP_GUIDE_MENU = %s;\n" % payload)

    print("Wrote %s" % out_path)
    for lang in LANGS:
        if lang in data:
            print(
                "  %s: %d groups, %d items"
                % (lang, len(data[lang]["groups"]), len(data[lang]["items"]))
            )
    if not ok:
        sys.stderr.write("VALIDATION FAILED: see warnings above.\n")
        sys.exit(1)
    print("Validation OK: all %d langs x %d groups x %d items."
          % (len(LANGS), EXPECTED_GROUPS, EXPECTED_ITEMS))


if __name__ == "__main__":
    main()
